"""migrate inicial

Revision ID: d3866785d9d9
Revises: 
Create Date: 2025-03-17 22:15:50.618372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3866785d9d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('autor', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    # ### end Alembic commands ###
